Feature/nd174 secrets accessible in plain text
ministryofjustice/staff-device-dns-dhcp-infrastructure pull request #321
Opened 2024-05-28 08:16 UTC by asifamirat00

ND-174 secrets accessible in plain text

2024-05-29 12:49 UTC, juddin927 approved these changes
LGTM

2024-05-29 13:06 UTC, jamesgreen-moj approved these changes
LGTM

2024-05-29 13:07 UTC, jamesgreen-moj requested changes

2024-05-29 13:07 UTC, jamesgreen-moj commented on modules/admin/iam.tf
> +    "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
This should not be full access

2024-05-29 15:33 UTC, asifamirat00 commented on modules/admin/iam.tf
> +    "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
Thanks for reviewing James, recommendations taken on board. Now using the AmazonSSMReadOnlyAccess policy for read only access to SSM parameter store

2024-05-30 08:44 UTC, jamesgreen-moj approved these changes
LGTM

2024-05-30 08:51 UTC, merged